version: '3.9'

networks:
  proxy: 
    external: true
    name: proxy

services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - type: bind
        source: ./config
        target: /opt/adguardhome/conf
      - type: bind
        source: /var/srv/adguardhome
        target: /opt/adguardhome/work
    ports:
    # DNS
      - "53:53/udp"
      - "53:53"
      - "853:853/udp"
      - "784:784/udp"
      - "5443:5443"
      - "5443:5443/udp"
      - "853:853"
      - "8853:8853/udp"
    labels:
      traefik.http.routers.adguardhome.rule: Host(`adguardhome1.network.nwest.xyz`)
      traefik.http.routers.adguardhome.tls: 'true'
      traefik.http.routers.adguardhome.service: adguardhome-adguardhome@docker
      traefik.http.routers.adguardhome.entrypoints: https
      traefik.http.services.adguardhome-adguardhome.loadbalancer.server.port: 443
      traefik.http.services.adguardhome-adguardhome.loadbalancer.server.scheme: https
